### ISSUE TITLE
Missing file link_pred_pytorch/train_models_baseline.py

### ISSUE THREAD

**Issue by saiteki-kai** [CongWeilin/DyFormer#1]
Hi, could you please provide the file `train_models_baseline.py` missing in the folder `link_pred_pytorch`?

**Comment by CongWeilin** [comment]
Hi, thank you for raising this issue. I didn't notice some files are not uploaded here. 

I just copied some files from my old repository and test locally, it seems working well. Could you please test it again. Please remember to first run `python write_script.py` to generate the model configurations before running the code.

**Comment by saiteki-kai** [comment]
Everything is working fine. Thank you.
